name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK Manually
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
        sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Generate Gradle Wrapper
      run: |
        GRADLE_VERSION="8.0"
        wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
        unzip -q gradle-${GRADLE_VERSION}-bin.zip
        export PATH=$PWD/gradle-${GRADLE_VERSION}/bin:$PATH
        gradle wrapper --gradle-version ${GRADLE_VERSION}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        unset ANDROID_SDK_ROOT
        ./gradlew assembleDebug --no-daemon

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/radyo.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: radyo
        path: app/build/outputs/apk/debug/radyo.apk
